#!/bin/bash

# Require Cross-Development Toolchain path (generated by SDK shell script)
if [ -z "$1" ]; then
    echo "Error: Please provide the cross-development toolchain path as an argument."
    echo "Example: $0 /opt/poky/4.0.2"
    exit 1
fi

CROSS_TOOLCHAIN_PATH="$1"

# Check if the provided Poky directory exists
if [ ! -d "$CROSS_TOOLCHAIN_PATH" ]; then
    echo "Error: The specified Poky directory '$CROSS_TOOLCHAIN_PATH' does not exist."
    exit 1
fi

echo "Using cross-development toolchain path: $CROSS_TOOLCHAIN_PATH"

# Setup the cross-compilation environment
source "$CROSS_TOOLCHAIN_PATH/environment-setup-armv8a-poky-linux"

# Check if $CC and $CXX are defined (verify cross-compilation environment)
if [[ -z "${CC}" || -z "${CXX}" ]]; then
    echo "Error: Cross-compilation environment wasn't set up properly."
    echo "Please source the environment setup script before running this script."
    exit 1
fi

ARCH=aarch64
echo "-I- Cross-Compiling For Hailo15 "
mkdir -p build/${ARCH}
cmake -H. -Bbuild/${ARCH}
cmake --build build/${ARCH}

if [[ -f "hailort.log" ]]; then
    rm hailort.log
fi
