namespace CocoClasses 
{
    public static class CocoEightyClasses 
    {
        public static Dictionary<int, string> Map { get; } = new Dictionary<int, string>()
        {
            { 0, "unlabeled" },
            { 1, "person" },
            { 2, "bicycle" },
            { 3, "car" },
            { 4, "motorcycle" },
            { 5, "airplane" },
            { 6, "bus" },
            { 7, "train" },
            { 8, "truck" },
            { 9, "boat" },
            { 10, "traffic light" },
            { 11, "fire hydrant" },
            { 12, "stop sign" },
            { 13, "parking meter" },
            { 14, "bench" },
            { 15, "bird" },
            { 16, "cat" },
            { 17, "dog" },
            { 18, "horse" },
            { 19, "sheep" },
            { 20, "cow" },
            { 21, "elephant" },
            { 22, "bear" },
            { 23, "zebra" },
            { 24, "giraffe" },
            { 25, "backpack" },
            { 26, "umbrella" },
            { 27, "handbag" },
            { 28, "tie" },
            { 29, "suitcase" },
            { 30, "frisbee" },
            { 31, "skis" },
            { 32, "snowboard" },
            { 33, "sports ball" },
            { 34, "kite" },
            { 35, "baseball bat" },
            { 36, "baseball glove" },
            { 37, "skateboard" },
            { 38, "surfboard" },
            { 39, "tennis racket" },
            { 40, "bottle" },
            { 41, "wine glass" },
            { 42, "cup" },
            { 43, "fork" },
            { 44, "knife" },
            { 45, "spoon" },
            { 46, "bowl" },
            { 47, "banana" },
            { 48, "apple" },
            { 49, "sandwich" },
            { 50, "orange" },
            { 51, "broccoli" },
            { 52, "carrot" },
            { 53, "hot dog" },
            { 54, "pizza" },
            { 55, "donut" },
            { 56, "cake" },
            { 57, "chair" },
            { 58, "couch" },
            { 59, "potted plant" },
            { 60, "bed" },
            { 61, "dining table" },
            { 62, "toilet" },
            { 63, "tv" },
            { 64, "laptop" },
            { 65, "mouse" },
            { 66, "remote" },
            { 67, "keyboard" },
            { 68, "cell phone" },
            { 69, "microwave" },
            { 70, "oven" },
            { 71, "toaster" },
            { 72, "sink" },
            { 73, "refrigerator" },
            { 74, "book" },
            { 75, "clock" },
            { 76, "vase" },
            { 77, "scissors" },
            { 78, "teddy bear" },
            { 79, "hair drier" },
            { 80, "toothbrush" }
        };
    }

    public static class CocoNinetyClasses 
{
    public static Dictionary<int, string> Map { get; } = new Dictionary<int, string>()
    {
        { 0, "unlabeled" },
        { 1, "person" },
        { 10, "traffic light" },
        { 11, "fire hydrant" },
        { 13, "stop sign" },
        { 14, "parking meter" },
        { 15, "bench" },
        { 16, "bird" },
        { 17, "cat" },
        { 18, "dog" },
        { 19, "horse" },
        { 20, "sheep" },
        { 2, "bicycle" },
        { 21, "cow" },
        { 22, "elephant" },
        { 23, "bear" },
        { 24, "zebra" },
        { 25, "giraffe" },
        { 27, "backpack" },
        { 28, "umbrella" },
        { 31, "handbag" },
        { 32, "tie" },
        { 33, "suitcase" },
        { 3, "car" },
        { 34, "frisbee" },
        { 35, "skis" },
        { 36, "snowboard" },
        { 37, "sports ball" },
        { 38, "kite" },
        { 39, "baseball bat" },
        { 40, "baseball glove" },
        { 41, "skateboard" },
        { 42, "surfboard" },
        { 43, "tennis racket" },
        { 4, "motorcycle" },
        { 44, "bottle" },
        { 46, "wine glass" },
        { 47, "cup" },
        { 48, "fork" },
        { 49, "knife" },
        { 50, "spoon" },
        { 51, "bowl" },
        { 52, "banana" },
        { 53, "apple" },
        { 54, "sandwich" },
        { 5, "airplane" },
        { 55, "orange" },
        { 56, "broccoli" },
        { 57, "carrot" },
        { 58, "hot dog" },
        { 59, "pizza" },
        { 60, "donut" },
        { 61, "cake" },
        { 62, "chair" },
        { 63, "couch" },
        { 64, "potted plant" },
        { 6, "bus" },
        { 65, "bed" },
        { 67, "dining table" },
        { 70, "toilet" },
        { 72, "tv" },
        { 73, "laptop" },
        { 74, "mouse" },
        { 75, "remote" },
        { 76, "keyboard" },
        { 77, "cellphone" },
        { 78, "microwave" },
        { 7, "train" },
        { 79, "oven" },
        { 80, "toaster" },
        { 81, "sink" },
        { 82, "refrigerator" },
        { 84, "book" }, 
        { 85, "clock" },
        { 86, "vase" },
        { 87, "scissors" },
        { 88, "teddy bear" },
        { 89, "hair drier" },
        { 8, "truck" },
        { 90, "tooth brush" },
        { 9, "boat" }
    };
}

}